export class Instructor {
    id: number | undefined; // ID generated by the backend
    name: string = '';
    gender: string = '';
    date_of_birth: string = ''; // Consider using a Date type
    department: string = '';
    email: string = '';
    contact_number: string = '';
  }
  