# Generated by Django 4.1.11 on 2023-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0005_enrollment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='remarks',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
